language: ruby
bundler_args: --without benchmark:site:development
cache: bundler
language: ruby
rvm:
 - 2.3.0

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

branches:
  only:
    - gh-pages
